### PR TITLE
Added comments, fixed indentation.

### PR DESCRIPTION
**Pull request by CodedChai**
I think I also fixed a bug in del_beg() for number 6. If I'm wrong feel free to revert it. All the comments are there and indentation is fixed.

### CODE REVIEW

**Comment by ajayns** [comment]
@skrillcon Hey! Thanks for the PR, great work! Have you compiled the code and tested each program before submitting the request?

**Comment by CodedChai** [comment]
I checked if they compiled and just now checked the one thing I did change which I should have before, sorry. Revert del_beg to what it was before in number 6.

void del_beg()
{
	if(head==NULL)
		printf("Underflow\n");
	else
		head=head->next;
	head->prev=NULL;
	
}

Other than that everything still compiles for me at least.

**Comment by ajayns** [comment]
@skrillcon Okay so make the fixes and commit to your branch. I'll merge the PR then!

**Comment by CodedChai** [comment]
I made the commit

**Comment by ajayns** [comment]
@skrillcon Thanks for the contribution!

**Pull request merged**
